<a href="https://colab.research.google.com/github/khush3012/Python-Lab/blob/main/NumPy%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 8 (Tools for EDA - Study of NumPy)
##Name : Khush Chauhan
##PRN : 25070123062
##Batch : Entc - A3
##Date : 18/02/2026


In [ ]:
# Why NumPy?
# Faster than lists
# Used for numerical computation
# Base for Pandas

In [6]:
# Declaration of NumPy

import numpy as np
a = np.array([10,20,30,40])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [7]:
# Dimensions of array

print(a.ndim)
print(b.ndim)

1
2


In [10]:
# Shape of array

a.shape

(4,)

In [11]:
b. shape

(2, 3)

In [12]:
a.dtype

dtype('int64')

In [13]:
b.dtype

dtype('int64')

In [14]:
# In-built functions using NumPy

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye((4)) #Gives diagonal matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.arange(1,30,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29])

In [25]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [30]:
print(b*2)
print(a+5)

[[ 2  4  6]
 [ 8 10 12]]
[15 25 35 45]


In [31]:
np.mean(a)

np.float64(25.0)

In [32]:
np.mean(b)

np.float64(3.5)

In [33]:
np.median(a)

np.float64(25.0)

In [34]:
np.median(b) #When mean and median are same, there are no outliers (data is clean)
#Always chose median when there is huge diff bw outliers)

np.float64(3.5)

In [35]:
np.max(a)

np.int64(40)

In [36]:
np.max(b)

np.int64(6)

In [37]:
np.min(a)

np.int64(10)

In [38]:
np.min(b)

np.int64(1)

In [39]:
np.sum(a)

np.int64(100)

In [40]:
np.sum(b)

np.int64(21)